from __future__ import annotations

from enum import Enum


class WorkflowStage(str, Enum):
    BACKLOG_INTAKE = "BACKLOG_INTAKE"
    PRODUCT_DEFINITION = "PRODUCT_DEFINITION"
    REQUIREMENTS_ANALYSIS = "REQUIREMENTS_ANALYSIS"
    ARCHITECTURE_DESIGN = "ARCHITECTURE_DESIGN"
    IMPLEMENTATION = "IMPLEMENTATION"
    PULL_REQUEST_CREATED = "PULL_REQUEST_CREATED"
    MERGE_CONFLICT_GATE = "MERGE_CONFLICT_GATE"
    ARCHITECTURE_REVIEW_GATE = "ARCHITECTURE_REVIEW_GATE"
    PEER_CODE_REVIEW_GATE = "PEER_CODE_REVIEW_GATE"
    TEST_VALIDATION_GATE = "TEST_VALIDATION_GATE"
    PRODUCT_ACCEPTANCE_GATE = "PRODUCT_ACCEPTANCE_GATE"
    DONE = "DONE"


class WorkflowStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"


class Decision(str, Enum):
    APPROVED = "APPROVED"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    REJECT = "REJECT"


class ArtifactStatus(str, Enum):
    DRAFT = "DRAFT"
    FINAL = "FINAL"
    SUPERSEDED = "SUPERSEDED"


class IntentCategory(str, Enum):
    VALIDATION = "VALIDATION"
    API_CHANGE = "API_CHANGE"
    DATA_MODEL = "DATA_MODEL"
    NEW_BEHAVIOR = "NEW_BEHAVIOR"
    BUG_FIX = "BUG_FIX"
    GENERAL = "GENERAL"


class EscalationStatus(str, Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"


class EventType(str, Enum):
    ERROR = "ERROR"
    CROSS_REPO_ARTIFACT_VALIDATED = "CROSS_REPO_ARTIFACT_VALIDATED"
    CROSS_REPO_ARTIFACT_COORDINATED = "CROSS_REPO_ARTIFACT_COORDINATED"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    STAGE_STARTED = "STAGE_STARTED"
    STAGE_COMPLETED = "STAGE_COMPLETED"
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    DECISION_MADE = "DECISION_MADE"
    TRANSITION_OCCURRED = "TRANSITION_OCCURRED"
    APPROVAL_RECORDED = "APPROVAL_RECORDED"
    ESCALATION_RAISED = "ESCALATION_RAISED"
    REVISION_STARTED = "REVISION_STARTED"
    REPO_SCANNED = "REPO_SCANNED"
    CHANGE_PLAN_GENERATED = "CHANGE_PLAN_GENERATED"
    FILES_MODIFIED = "FILES_MODIFIED"
    PATCH_APPLIED = "PATCH_APPLIED"
    PATCH_ROLLED_BACK = "PATCH_ROLLED_BACK"
    TEST_EXECUTION_STARTED = "TEST_EXECUTION_STARTED"
    TEST_EXECUTION_COMPLETED = "TEST_EXECUTION_COMPLETED"
    TEST_PASSED = "TEST_PASSED"
    TEST_FAILED = "TEST_FAILED"
    HUMAN_FEEDBACK_RECORDED = "HUMAN_FEEDBACK_RECORDED"
    ESCALATION_RESOLVED = "ESCALATION_RESOLVED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
