"""
Dashboard action runners: subprocess calls back into the workflow engine.
"""
from __future__ import annotations

import os
import subprocess
import sqlite3
import sys
from pathlib import Path
from autonomous_delivery.ui.config import BASE_DIR, UI_SQLITE_PATH


def _as_path(path_value: str) -> Path:
    path = Path(path_value)
    if path.is_absolute():
        return path
    return BASE_DIR / path


def _workflow_exists_in_sqlite(db_path: Path, workflow_id: str) -> bool:
    try:
        conn = sqlite3.connect(str(db_path))
        try:
            row = conn.execute(
                "SELECT 1 FROM workflow_states WHERE workflow_id = ? LIMIT 1",
                (workflow_id,),
            ).fetchone()
            return row is not None
        finally:
            conn.close()
    except Exception:
        return False

    # st.write(f"## {artifact['name']}")  # noqa: E501  # FIXED: moved or removed stray indented line
    candidates: list[Path] = []

    env_sqlite = os.getenv("ASF_SQLITE_PATH")
    if env_sqlite:
        candidates.append(_as_path(env_sqlite))

    candidates.append(_as_path(UI_SQLITE_PATH))
    candidates.append(_as_path("generated_workspace/asf_state.db"))

    generated_workspace = BASE_DIR / "generated_workspace"
    if generated_workspace.exists():
        candidates.extend(sorted(generated_workspace.glob("*.db")))

    unique_candidates: list[Path] = []
    seen: set[str] = set()
    for candidate in candidates:
        key = str(candidate.resolve()) if candidate.exists() else str(candidate)
        if key in seen:
            continue
        seen.add(key)
        unique_candidates.append(candidate)

    existing_candidates = [candidate for candidate in unique_candidates if candidate.exists()]
    for candidate in existing_candidates:
        if _workflow_exists_in_sqlite(candidate, workflow_id):
            return candidate, existing_candidates

    return None, existing_candidates


def _format_path_for_message(path: Path) -> str:
    try:
        return str(path.relative_to(BASE_DIR))
    except ValueError:
        return str(path)


def run_workflow_from_dashboard(
    seed_repo_name: str,
    repo_url: str | None = None,
    repo_ref: str | None = None,
) -> tuple[bool, str]:
    try:
        env = {
            **os.environ,
            "PYTHONPATH": "src",
            "ASF_SEED_REPO": seed_repo_name,
            "ASF_PERSISTENCE_BACKEND": "sqlite",
            "ASF_SQLITE_PATH": UI_SQLITE_PATH,
        }
        if repo_url:
            env["ASF_REPO_URL"] = repo_url
        if repo_ref:
            env["ASF_REPO_REF"] = repo_ref

        result = subprocess.run(
            [sys.executable, "-m", "ai_software_factory"],
            cwd=BASE_DIR,
            env=env,
            capture_output=True,
            text=True,
        )
    except Exception as exc:
        return False, f"Failed to run workflow: {exc}"

    output = ((result.stdout or "") + "\n" + (result.stderr or "")).strip()
    if result.returncode != 0:
        return False, output[-4000:] if output else "Workflow failed with no output."
    return True, output[-4000:] if output else "Workflow completed successfully."


def run_escalation_demo_from_dashboard() -> tuple[bool, str]:
    try:
        result = subprocess.run(
            [sys.executable, "scripts/demo_escalation.py"],
            cwd=BASE_DIR,
            env={
                **os.environ,
                "PYTHONPATH": "src",
                "ASF_PERSISTENCE_BACKEND": "sqlite",
                "ASF_SQLITE_PATH": UI_SQLITE_PATH,
            },
            capture_output=True,
            text=True,
        )
    except Exception as exc:
        return False, f"Failed to run escalation demo: {exc}"

    output = ((result.stdout or "") + "\n" + (result.stderr or "")).strip()
    if result.returncode != 0:
        return False, output[-4000:] if output else "Escalation demo failed with no output."
    return True, output[-4000:] if output else "Escalation demo completed successfully."


def run_resume_from_dashboard(
    workflow_id: str,
    human_response: str,
    resume_stage: str = "IMPLEMENTATION",
    responder: str = "human_operator",
    resume_max_steps: int = 120,
    response_template: str = "",
) -> tuple[bool, str]:
    resolved_sqlite, checked_paths = _resolve_sqlite_path_for_workflow(workflow_id)
    if resolved_sqlite is None:
        checked = ", ".join(_format_path_for_message(path) for path in checked_paths) if checked_paths else "none"
        return (
            False,
            (
                f"Resume blocked: workflow_id '{workflow_id}' was not found in available SQLite state stores. "
                f"Checked: {checked}. Run escalation from dashboard first, or select a workflow generated by this workspace."
            ),
        )

    try:
        result = subprocess.run(
            [sys.executable, "-m", "ai_software_factory"],
            cwd=BASE_DIR,
            env={
                **os.environ,
                "PYTHONPATH": "src",
                "ASF_PERSISTENCE_BACKEND": "sqlite",
                "ASF_SQLITE_PATH": str(resolved_sqlite),
                "ASF_RESUME_WORKFLOW_ID": workflow_id,
                "ASF_HUMAN_RESPONSE": human_response,
                "ASF_RESUME_STAGE": resume_stage,
                "ASF_RESUME_RESPONDER": responder,
                "ASF_RESUME_MAX_STEPS": str(resume_max_steps),
                "ASF_HUMAN_RESPONSE_TEMPLATE": response_template,
            },
            capture_output=True,
            text=True,
        )
    except Exception as exc:
        return False, f"Failed to resume workflow: {exc}"

    output = ((result.stdout or "") + "\n" + (result.stderr or "")).strip()
    if result.returncode != 0:
        return False, output[-4000:] if output else "Workflow resume failed with no output."
    return True, output[-4000:] if output else "Workflow resumed successfully."


def latest_escalation_reason(events: list[dict]) -> str | None:
    for event in reversed(events):
        if event.get("event_type") != "ESCALATION_RAISED":
            continue
        payload = event.get("payload", {})
        reason = payload.get("reason")
        if isinstance(reason, str) and reason.strip():
            return reason.strip()
    return None
